#!/usr/bin/env bash
# regen-slug-fixtures.sh — regenerate the snapshot fixture used by
# test/contract/slug_test.go against upstream github-slugger.
#
# The contract test pins rfc-api's slug output to whatever the
# pinned github-slugger version emits for the same input. To pick
# up an upstream behavior change, bump SLUGGER_VERSION below and
# re-run this script, then commit both the regenerated fixture and
# the version bump together — never silently.
#
# rfc-site re-runs its own equivalent against the same pinned
# version (independent re-derivation per IMPL-0006 OQ3=B) so the
# two repos triangulate on upstream rather than copy-blindly from
# each other.

set -euo pipefail

# Pin the upstream slug algorithm. Bump deliberately, with the
# regenerated fixture + this bump in the same commit.
SLUGGER_VERSION="2.0.0"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INPUT_PATH="${REPO_ROOT}/test/contract/testdata/slug_fixtures_input.json"
OUTPUT_PATH="${REPO_ROOT}/test/contract/testdata/slug_fixtures.json"

if [[ ! -f "${INPUT_PATH}" ]]; then
  echo "error: input fixture not found at ${INPUT_PATH}" >&2
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "error: node not on PATH (mise install)" >&2
  exit 1
fi
if ! command -v npm >/dev/null 2>&1; then
  echo "error: npm not on PATH (mise install)" >&2
  exit 1
fi

WORKDIR="$(mktemp -d)"
trap 'rm -rf "${WORKDIR}"' EXIT

(
  cd "${WORKDIR}"
  npm init -y >/dev/null 2>&1
  npm install --silent --no-audit --no-fund "github-slugger@${SLUGGER_VERSION}" >/dev/null
)

# Write the regen script into WORKDIR so its bare 'github-slugger'
# import resolves against the just-installed node_modules.
cat > "${WORKDIR}/regen.mjs" <<'NODE'
import { readFileSync, writeFileSync } from "node:fs";
import GithubSlugger, { slug } from "github-slugger";

const [, , inputPath, outputPath, version] = process.argv;
const raw = JSON.parse(readFileSync(inputPath, "utf8"));

const pure = raw.pure.map((s) => ({ input: s, expected: slug(s) }));

const collision_groups = raw.collision_groups.map((g) => {
  const sl = new GithubSlugger();
  return {
    name: g.name,
    sequence: g.sequence.map((s) => ({ input: s, expected: sl.slug(s) })),
  };
});

const out = {
  _about:
    "Snapshot generated by scripts/regen-slug-fixtures.sh from pinned github-slugger@" +
    version +
    ". Regenerate via `make regen-slug-fixtures`. See IMPL-0006 Phase 3.",
  _slugger_version: version,
  pure,
  collision_groups,
};

writeFileSync(outputPath, JSON.stringify(out, null, 2) + "\n");
NODE

(
  cd "${WORKDIR}"
  node --no-warnings "${WORKDIR}/regen.mjs" "${INPUT_PATH}" "${OUTPUT_PATH}" "${SLUGGER_VERSION}"
)

echo "wrote ${OUTPUT_PATH} (github-slugger@${SLUGGER_VERSION})"
